// @generated by protobuf-ts 2.9.3 with parameter generate_dependencies,keep_enum_prefix
// @generated from protobuf file "auth/auth.proto" (package "com.pager.api", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { RefreshResponse } from "./auth";
import type { RefreshRequest } from "./auth";
import type { SearchUsersResponse } from "./auth";
import type { SearchUsersRequest } from "./auth";
import type { Empty } from "../common/common";
import type { RegistrationRequest } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Token } from "./auth";
import type { LoginRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service com.pager.api.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: Login(com.pager.api.LoginRequest) returns (com.pager.api.Token);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, Token>;
    /**
     * @generated from protobuf rpc: Registration(com.pager.api.RegistrationRequest) returns (com.pager.api.Empty);
     */
    registration(input: RegistrationRequest, options?: RpcOptions): UnaryCall<RegistrationRequest, Empty>;
    /**
     * @generated from protobuf rpc: SearchUsersByIdentifier(com.pager.api.SearchUsersRequest) returns (com.pager.api.SearchUsersResponse);
     */
    searchUsersByIdentifier(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, SearchUsersResponse>;
    /**
     * @generated from protobuf rpc: Refresh(com.pager.api.RefreshRequest) returns (com.pager.api.RefreshResponse);
     */
    refresh(input: RefreshRequest, options?: RpcOptions): UnaryCall<RefreshRequest, RefreshResponse>;
}
/**
 * @generated from protobuf service com.pager.api.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login(com.pager.api.LoginRequest) returns (com.pager.api.Token);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, Token> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, Token>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Registration(com.pager.api.RegistrationRequest) returns (com.pager.api.Empty);
     */
    registration(input: RegistrationRequest, options?: RpcOptions): UnaryCall<RegistrationRequest, Empty> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegistrationRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchUsersByIdentifier(com.pager.api.SearchUsersRequest) returns (com.pager.api.SearchUsersResponse);
     */
    searchUsersByIdentifier(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, SearchUsersResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchUsersRequest, SearchUsersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Refresh(com.pager.api.RefreshRequest) returns (com.pager.api.RefreshResponse);
     */
    refresh(input: RefreshRequest, options?: RpcOptions): UnaryCall<RefreshRequest, RefreshResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshRequest, RefreshResponse>("unary", this._transport, method, opt, input);
    }
}
