name: production

on:
  push:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: build docker container
        run: docker build -t yruzik/pager-web .
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: publish docker container
        run: docker push yruzik/pager-web
